Repository JoheeYeom0103/TicktHub, pull requests merged in 2024-03, with the labels that each got.

#35 two design patterns
  .DS_Store
  Requirements/DesignPatterns.md
Labels: documentation

#39 trying to merge the updated design patterns (that include reviewer's comments)
  Requirements/DesignPatterns.md
Labels: documentation

#37 Add files via upload
  Requirements/COSC310_M3.pdf
Labels: documentation

#38 Edit/Delete Event Script bug fixes
  TicketHubUpdatedCode_Mar2.zip
  TicketHubUpdatedCode_Mar3.zip
  editDeleteEventScript.js
Labels: front end development

#51 added Joy's reviews
  Requirements/DesignPatterns.md
Labels: documentation

#40 Update Shopping Cart Page
  .DS_Store
  adminDashboard.html
  browseTickets.html
  buyer_personalinfo.html
  createtickets.html
  css/.DS_Store
  css/adminDashboardStyling.css
  css/browseTicketsStyling.css
  css/createTicketsStyling.css
  css/editDeleteEventStyling.css
  css/headerFooter.css
  css/leftnav.css
  css/loginStyling.css
  css/myTicketsStyling.css
  css/orderconfirm.css
  css/payment.css
  css/paymentinfo.css
  css/payoutInfo.css
  css/personalInfoStyling.css
  css/salesManageEvents.css
  css/shoppingcart.css
  css/signupStyling.css
  images/.DS_Store
  images/Placeholder-01.jpg
  images/Placeholder.ai
  images/SearchIcon-01.png
  images/cateogry.svg
  images/facebook.png
  images/icons.ai
  images/insta.png
  images/paypal.png
  images/title.svg
  images/twitter (1).png
  images/usericon-01.svg
  login.html
  mytickts.html
  orderconfirm.html
  payment.html
  paymentinfo.html
  payoutinfo.html
  salesManageEvents.html
  script/.DS_Store
  script/adminDashboardScript.js
  script/createtickets.js
  script/editDeleteEventScript.js
  script/loginScript.js
  script/paymentinfo.js
  script/payoutinfo.js
  script/personalInfoValidation.js
  script/shoppingcart.js
  script/signupScript.js
  seller_personalinfo.html
  shoppingcart.html
  signup.html
Labels: front end development, testing

#36 Add files via upload
  Requirements/Note Feb 24, 2024.pdf
Labels: documentation

#53 Added scrum meeting and completed UML diagram
  Requirements/COSC 310_ Testing Plan .pdf
  Requirements/COSC310_M3 UML diagram.pdf
  Requirements/COSC310_M3.pdf
  Requirements/M3_TicketHub_UML.pdf
  Scrum meetings/SCRUM-MEETING-week 8.docx
Labels: documentation

#69 testing ddl via insert statements & select statements #49
  .DS_Store
  UpdatedTicketHubDDL.sql
Labels: testing

#70 Added Scrum meeting for week 9.
  Scrum meetings/SCRUM-MEETING-Week 9.docx
Labels: documentation

#81 Added backend functionality to browse tickets and back button
  backend/browsetickets.php
  browseTickets.html
  css/headerFooter.css
Labels: back end development
